# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'inertial' do
   pod 'Charts'
   pod 'MotionKit'
   pod 'Realm'
   pod 'RealmSwift'
   pod 'FileKit'
   pod 'SwiftCharts'
   pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
   pod 'CocoaAsyncSocket'
end

use_frameworks!
