# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'inertial' do
   pod 'Charts'
   pod 'MotionKit'
   pod 'Realm'
   pod 'FileKit'
   pod 'SwiftCharts'
end

use_frameworks!
